server:
  port: 9030
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tracks
      username: user
      password: password
      authentication-database: admin
      auto-index-creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ping
  resource: track-service
  public-client: true