version: '3.9'
services:
  config:
    build: config-service/.
    hostname: config
    container_name: config-server
    ports:
      - 8888:8888
    networks:
      - ping
  eureka:
    build: discovery-service/.
    hostname: discovery
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - ping
  auth:
    build: auth-service/.
    hostname: auth
    container_name: authorization-server
    ports:
      - 8080:8080
    networks:
      - ping
networks:
  ping:
    name: ping-network