version: '3.9'
services:
  user-db:
    image: mysql:5.7
    hostname: userdb
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: 'user_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - ping-only
    ports:
      - 3306:3306
  postgres:
    image: postgres:13.2
    container_name: users-postgres
    hostname: users
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - ping-only
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak-server
    hostname: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: users
      DB_USER: user
      DB_PASSWORD: password
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./volumes/keycloak/imports:/opt/jboss/keycloak/imports
    command:
      - '-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json'
    ports:
      - 8080:8080
    networks:
      - pings
networks:
  ping-only:
    name: ping-only-network