server:
  port: 9000
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ping
  resource: user-service
  public-client: true
keycloak-user:
  admin:
    username: user
    password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/