server:
  port: 8888
spring:
  application:
    name: config
  profiles:
    active:
      - native
      - dev
  cloud:
    config.server.native.search-locations:
      - classpath:/config
      - classpath:/config/{application}
      - classpath:/config/{application}/{profile}