CREATE TABLE IF NOT EXISTS `users`
(
    `id`       INT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(64) UNIQUE NOT NULL,
    `password` VARCHAR(256)       NOT NULL,
    `email`    VARCHAR(64) UNIQUE NOT NULL
)