spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: schedules
      username: user
      password: password
      authentication-database: admin
      auto-index-creation: true
  kafka:
    producer:
      bootstrap-server: localhost:29092
      topic:
        schedule:
          name: schedule
          partitions: 1
          replication-factor: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false